### PR TITLE
Update getallheaders.php

### PR DESCRIPTION
**Pull request by WinterSilence**

### CODE REVIEW

**Comment by peter279k** [comment]
The Travis CI build is still failed due to failed assertion.

The failed assertion message is as follows:

```
1) getallheaders\Tests\GetAllHeadersTest::testWorks with data set #4 ('Content-MD5', array('aef123'), array('aef123', 'fea321'))
Error testing Content-MD5 works.
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    'Content-Md5' => 'aef123'
+    'Content-MD5' => 'aef123'
 )
/home/travis/build/ralouphie/getallheaders/tests/GetAllHeadersTest.php:18
```

This updating work seems to be incorrect. Please check that.

**Comment by WinterSilence** [comment]
@peter279k test failed because i send 2 PR, merge it

**Comment by peter279k** [comment]
I think you can merge these PRs to one PR if possible.

And it will be clear for us to review PR.

**Comment by WinterSilence** [comment]
@peter279k i dont use this repo, this PR only for help u fixing bugs

**Comment by peter279k** [comment]
@ralouphie, could you concern about this?

It seems to be a bug.

**Comment by WinterSilence** [comment]
@peter279k seems? u always can [check it](https://www.iana.org/assignments/message-headers/message-headers.xhtml)

**Comment by peter279k** [comment]
Hi @WinterSilence, thanks for your reply.

I will check that and create PR to correct this header :).

**Pull request closed without merging**
