### PR TITLE
Add .gitattributes

### PR DESCRIPTION
**Pull request by reedy**
Stops composer exporting files that aren't needed in vendor folders

### CODE REVIEW

**Comment by willemstuursma** [comment]
Checkout out the build failure, it's unrelated to these changes. PHP 5.3 can no longer be built on this distro.

**Comment by reedy** [comment]
> Checkout out the build failure, it's unrelated to these changes. PHP 5.3 can no longer be built on this distro.

How much do you care about PHP 5.3 support? Dropping it from travis (so it's not tested) and keeping the version in composer.json isn't great, but could be done. Else maybe it's time to bump to supporting only PHP 5.5, 5.6 or even 7+ at this point? :)

**Comment by ralouphie** [comment]
Thanks for the contribution!

**Comment by glensc** [comment]
you can add `dist: precise` to build for 5.3:

- https://github.com/eventum/rpc/blob/v4.3.0/.travis.yml#L11

**Pull request merged**
